coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "src/**"
    patch:
      default:
        target: auto
        threshold: 20%
        paths:
          - "src/**"

ignore:
  - "tests/**"
  - "examples/**"
  - "**/*test*.c"
  - "**/*test*.h"

comment:
  layout: "diff, files"
  behavior: default