coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - src/
  
  ignore:
    - "tests"
    - "examples"
    - "**/*test*.c"
    - "**/*test*.h"
