sonar.organization=lucianodato
sonar.projectKey=lucianodato_libspecbleach
sonar.python.version=3.9
sonar.sources=src,include,extras/src,extras/include
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.cfamily.cobertura.reportPaths=build/coverage.xml
